### ISSUE TITLE
help wanted.

### ISSUE THREAD

**Issue by pmirla** [amamenko/react-buzzfeed-quiz#3]
#helpwanted 
Hello. Thanks for this app.
How do we keep track of all the answers? 
Call back functions on answer selection() doesn't have reference to selected answer.

**Comment by pmirla** [comment]
Thank you, Avi. Would it be possible to show a response after the user picks an answer choice for a question? We are now able to show a response after all quiz questions are answered. And, can we embed videos in the question box?Thank you

**Comment by amamenko** [comment]
1. Do you mean triggering a result early on  a specific answer selection without having all the questions finished? I can make that a feature, sure.
2. At the moment, the closest you can get to embedding a video is by transforming the video into a GIF and setting it as the backgroundImageSrc. This just sets the "src" attribute on an HTML img tag. For videos, I would need to conditionally set that as a video tag and check for the three supported video formats in HTML: MP4, WebM, and OGG.

**Comment by pmirla** [comment]
#1. Would be great to show a message box below the question after the question is answered.
example from nytimes quiz. Thanks 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/5429924/155764728-dec04eca-4576-4666-adde-408d3255e0a3.png">

**Comment by pmirla** [comment]
hello. I just wanted to ask if you are planning to add a response feature after answering a question. Thank you

**Comment by amamenko** [comment]
I believe BuzzFeed implements something like this on their trivia questions:

<img width="744" alt="Screen Shot 2022-03-07 at 7 40 35 PM" src="https://user-images.githubusercontent.com/49536715/157142798-90658348-f7c6-467b-9dc9-b36b5ddc8101.png">

Is this something like what you were referring to? If so, I can definitely add the feature to the quiz component, as well.

**Comment by pmirla** [comment]
That would be great .
Kind regards

**Comment by pmirla** [comment]
Thank you
